name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World - This is first Job!"
  my-job2:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "This is 2nd Job!"
